2018-11-21 05:20:06
An exception occur: com.cludove.dirigible.gear.exception.BaseException

java.sql.SQLRecoverableException
java.sql.SQLRecoverableException, Closed Connection
oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2250)
oracle.jdbc.driver.PhysicalConnection.commit(PhysicalConnection.java:2353)
oracle.jdbc.driver.PhysicalConnection.commit(PhysicalConnection.java:2403)
com.cludove.dirigible.gear.resource.database.connection.BaseConnection.commit(BaseConnection.java:150)
com.cludove.dirigible.hold.db.DBData.closeConnections(DBData.java:454)
com.cludove.hinge.processor.thread.DetectorProcessor.m_ALLATORIxDEMO(DetectorProcessor.java:83)
com.cludove.hinge.processor.thread.DetectorProcessor.process(DetectorProcessor.java:26)
jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.base/java.lang.reflect.Method.invoke(Unknown Source)
com.cludove.compass.buddle.Processor.run(Processor.java:80)
java.base/java.lang.Thread.run(Unknown Source)
.END.

2018-11-21 05:20:06
An exception occur: com.cludove.dirigible.gear.exception.BaseException

java.sql.SQLRecoverableException
java.sql.SQLRecoverableException, Closed Connection
oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2250)
oracle.jdbc.driver.PhysicalConnection.commit(PhysicalConnection.java:2353)
oracle.jdbc.driver.PhysicalConnection.commit(PhysicalConnection.java:2403)
com.cludove.dirigible.gear.resource.database.connection.BaseConnection.remove(BaseConnection.java:83)
com.cludove.dirigible.hold.db.DBData.closeConnections(DBData.java:461)
com.cludove.hinge.processor.thread.DetectorProcessor.m_ALLATORIxDEMO(DetectorProcessor.java:83)
com.cludove.hinge.processor.thread.DetectorProcessor.process(DetectorProcessor.java:26)
jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.base/java.lang.reflect.Method.invoke(Unknown Source)
com.cludove.compass.buddle.Processor.run(Processor.java:80)
java.base/java.lang.Thread.run(Unknown Source)
.END.

2018-11-21 05:20:15
An exception occur: com.cludove.dirigible.gear.exception.BaseException

java.sql.SQLRecoverableException
java.sql.SQLRecoverableException, Closed Connection
oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2250)
oracle.jdbc.driver.PhysicalConnection.commit(PhysicalConnection.java:2353)
oracle.jdbc.driver.PhysicalConnection.commit(PhysicalConnection.java:2403)
com.cludove.dirigible.gear.resource.database.connection.BaseConnection.commit(BaseConnection.java:150)
com.cludove.dirigible.hold.db.DBData.closeConnections(DBData.java:454)
com.cludove.hinge.processor.thread.DetectorProcessor.m_ALLATORIxDEMO(DetectorProcessor.java:83)
com.cludove.hinge.processor.thread.DetectorProcessor.process(DetectorProcessor.java:26)
jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.base/java.lang.reflect.Method.invoke(Unknown Source)
com.cludove.compass.buddle.Processor.run(Processor.java:80)
java.base/java.lang.Thread.run(Unknown Source)
.END.

2018-11-21 05:20:15
An exception occur: com.cludove.dirigible.gear.exception.BaseException

java.sql.SQLRecoverableException
java.sql.SQLRecoverableException, Closed Connection
oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2250)
oracle.jdbc.driver.PhysicalConnection.commit(PhysicalConnection.java:2353)
oracle.jdbc.driver.PhysicalConnection.commit(PhysicalConnection.java:2403)
com.cludove.dirigible.gear.resource.database.connection.BaseConnection.remove(BaseConnection.java:83)
com.cludove.dirigible.hold.db.DBData.closeConnections(DBData.java:461)
com.cludove.hinge.processor.thread.DetectorProcessor.m_ALLATORIxDEMO(DetectorProcessor.java:83)
com.cludove.hinge.processor.thread.DetectorProcessor.process(DetectorProcessor.java:26)
jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.base/java.lang.reflect.Method.invoke(Unknown Source)
com.cludove.compass.buddle.Processor.run(Processor.java:80)
java.base/java.lang.Thread.run(Unknown Source)
.END.

2018-11-21 05:20:16
websocket消息推送异常:The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method,消息内容:com.cludove.dirigible.gear.websocket.SocketMessage@56c83a80

2018-11-21 05:20:16
websocket消息推送异常:The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method,消息内容:com.cludove.dirigible.gear.websocket.SocketMessage@3c820f4a

2018-11-21 05:20:16
websocket消息推送异常:The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method,消息内容:com.cludove.dirigible.gear.websocket.SocketMessage@300bfb5c

2018-11-21 05:20:16
websocket消息推送异常:The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method,消息内容:com.cludove.dirigible.gear.websocket.SocketMessage@50e20ade

2018-11-21 05:20:16
websocket消息推送异常:The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method,消息内容:com.cludove.dirigible.gear.websocket.SocketMessage@78de6cb8

2018-11-21 05:20:19
ConnectionPool's reapConnections[jdbc:mysql://192.168.150.100:3306/infoinge_test1]: 0

2018-11-21 05:20:40
ConnectionPool's reapConnections[jdbc:mysql://192.168.150.100:3306/infoinge_test1]: 0

2018-11-21 05:20:45
ConnectionPool's reapConnections[jdbc:oracle:thin:@192.168.150.100:1521:orcl]: 139

